### ISSUE TITLE
Works with the Home app, but not with Siri?

### ISSUE THREAD

**Issue by hepcat72** [RockyGJ/homebridge-commander#5]
So I got this working to use with Etekcity outlets and the pilight-send command, but for some reason, when I try to use Siri to control the outlet, Siri replies:

"Sorry, Rob, I wasn't able to find anything like that in your home this time."

I tried changing the homebridge username, deleting the persist directory, and removing and re-adding homebridge from the Home app.  These steps have worked for me in the past when Siri didn't work but the Home app did.  I've done everything multiple times.

I based the script on the example you provided using the outlet type.

When I use the home app, the log populates correctly.  I added echos for every possibility.  I can run the script manually to turn the outlet on & off.  I even created a mechanism to save the powerstate in a separate file (because etekcity outlets don't have a way to report their state) and the button in the home app correctly shows whether the outlet is on or off.

Siri works with everything else I have setup in homebridge (including liftmaster2, wemo, and CEC to control my TV).

I'm stuck.  Do you have any insights you can provide that will make Siri work with homebridge-commander?

**Comment by RockyGJ** [comment]
Siri has sometimes an issue with the name of outlets. When the outlet has a name which is similar of an application or function within Siri the Siri command will not function. To check if this is the issue I suggest you try to rename the outlet and try with Siri again.  

If that does not work you can try to add the outlet to a new scene in the home app and try to start the scene with Siri.

The plugin itself has no interface with Siri directly so is just passes the devices to HomeKit through homebridge. The home application and Siri get there information from HomeKit directly. Is it possible that you use a device which is not listed in the official Apple home application? Some device types are not supported within the home application. Those device types can be added to a scene with 3rd party application like the Eve app.

**Comment by hepcat72** [comment]
Yup. That’s it. I named the outlet “lights”. I was playing around with it. If I leave the name as “lights”, Siri will control them if I say things like:

* turn on the quote lights end quote
* turn on the lights outlet
* turn on the lights plug

I may try the name lamps or family room lights. Or... I wonder if changing the type to lightbulb will make “lights” work...

Thanks!
